# Generated by Django 4.2.7 on 2023-11-04 18:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for the office.', max_length=20, null=True, verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, help_text='Fax number for the office.', max_length=20, null=True, verbose_name='Fax Number')),
                ('email_address', models.EmailField(blank=True, help_text='Email address for the office.', max_length=255, null=True, verbose_name='Email Address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], help_text='Day of the week this time applies to.', max_length=1, unique=True, verbose_name='Day of Week')),
                ('open', models.TimeField(blank=True, help_text='Time the office opens.', null=True, verbose_name='Open Time')),
                ('close', models.TimeField(blank=True, help_text='Time the office closes.', null=True, verbose_name='Close Time')),
                ('closed', models.BooleanField(default=False, help_text='Is the office closed on this day?', verbose_name='Closed')),
                ('office', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='home.office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Office Hours',
                'verbose_name_plural': 'Office Hours',
                'ordering': ['day'],
            },
        ),
        migrations.AddConstraint(
            model_name='officehours',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('closed', True), ('open__isnull', True), ('close__isnull', True)), models.Q(('closed', False), ('open__isnull', False), ('close__isnull', False)), models.Q(('closed', False), ('open__isnull', True), ('close__isnull', True)), _connector='OR'), name='open_close'),
        ),
    ]
